# server
server:
  port: 8081
  servlet:
    context-path: /boot

# database
spring:
  datasource:
    url: jdbc:mysql://tz_mysql:3306/mystudy
    driver-class-name:  com.mysql.cj.jdbc.Driver
    username: root
    password: root

  # jpa
  jpa:
    hibernate:
      ddl-auto: update  # 建表策略
    show-sql: true  #显示SQL语句